# See man 5 tinyproxy
# TCP stream forwarding.
listen tcp :80     tcp 10.0.1.1:80
listen tcp :443    tcp 10.0.1.1:443    proxy_v2,keep_alive

# TCP # listener to UNIX stream backend.
listen tcp  :12990                unix /tmp/test.sock

# UDP datagram forwarding.
listen udp :12345  udp 10.0.1.1:12345  idle_timeout=10,connect_timeout=17
listen udp :19132  udp 10.0.1.1:19132

# UDP # listener to UNIX datagram backend.
listen udp :13000  unix-dgram /tmp/testd.sock

# Builtin TCP test backends.
listen tcp :12995  builtin client_addr
listen tcp :12996  builtin hang         idle_timeout=3,connect_timeout=1
listen tcp :12997  builtin discard
listen tcp :12998  builtin close
listen tcp :12999  builtin log_conn
listen tcp :8080   builtin http_ok

# Builtin UDP test backends.
listen udp :12995  builtin client_addr
listen udp :12996  builtin hang
listen udp :12997  builtin discard
listen udp :12998  builtin close
listen udp :8080   builtin http_ok

# Static file TCP backends.
listen tcp :14000  file examples/http-response.txt

listen unix /tmp/tinyproxy-chain-1.sock file examples/http-response.txt
listen tcp  :13002                      unix /tmp/tinyproxy-chain-1.sock
listen tcp  :13003                      tcp  127.0.0.1:13002
listen unix /tmp/tinyproxy-chain-4.sock tcp  127.0.0.1:13003
listen tcp  :14001                      unix /tmp/tinyproxy-chain-4.sock
